/*
 * Generated by ActionName
 * Template path: templates/java/JavaClass.vtl
 */
package com.xyz.passport.action;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.xyz.system.model.User;
import com.xyz.system.service.ISecurityService;
import com.xyz.util.Page;
import com.xyz.util.PropertyFilter;
import com.xyz.util.SpringSecurityUtil;

/**
 * 创建日期: 08-17-2009
 * 
 * XDoclet definition:
 * 
 * 作者:Val
 */
@Controller
public class IndexAction {
	@Autowired
	private ISecurityService sfacade;

	@RequestMapping("/index")
	public String execute(HttpServletRequest req, ModelMap model) {
		User user = SpringSecurityUtil.getCurrentUser();
		if (user != null && user.getShop() != null) {
			return "redirect:/index.html";
		} else {
			user = (User) req.getAttribute("user");
			if (user != null) {
				List<PropertyFilter> filters = new ArrayList<PropertyFilter>();
				filters
						.add(new PropertyFilter("EQ_shopKey", user.getShopKey()));
				// 查询该店所有可登录用户
				Page<User> page = new Page<User>(5);
				page.setStart(0);
				page = sfacade.queryUsers(page, filters);
				model.put("users", page.getResult());
				model.put("j_username", user.getUsername());
				model.put("j_password", "zhikebao");
			}
			return "login";
		}
	}

	@RequestMapping("/88688810.html")
	@ResponseBody
	public String drawStatic(HttpServletRequest request) {
		Cookie[] cookies = request.getCookies();
		System.out.println("获取到请求值列表：");
		Enumeration enums = request.getHeaderNames();
		while (enums.hasMoreElements()) {

			System.out.println(request
					.getHeader(enums.nextElement().toString()));
		}

		System.out.println(request.getHeaderNames().toString());
		System.out.println("获取到的Cookie列表：");
		System.out.println("获取到的Cookie列表：");
		for (Cookie cook : cookies) {
			System.out.println(cook.getName() + "=" + cook.getValue());
		}
		return "<script type='text/javascript'></script>";
	}
}