package com.xyz.acl.model;

// Generated 2009-12-20 12:00:06 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclClass generated by hbm2java
 */
@Entity
@Table(name = "acl_class", uniqueConstraints = @UniqueConstraint(columnNames = "CLASS"))
public class AclClass extends AbstractSecureObject  {

	@Column(name = "CLASS", unique = true, nullable = false, length = 128)
	private String class_;

	public AclClass() {
	}

	public AclClass(String class_) {
		this.class_ = class_;
	}


	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
