package com.xyz.acl.model;

// Generated 2009-12-20 12:00:06 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AclEntry generated by hbm2java
 */
@Entity
@Table(name = "acl_entry")
public class AclEntry  extends AbstractSecureObject  {

	private long aclObjectIdentity;
	private int aceOrder;
	private long sid;
	private int mask;
	private Boolean granting;
	private Boolean auditSuccess;
	private Boolean auditFailure;

	public AclEntry() {
	}

	public AclEntry(long aclObjectIdentity, int aceOrder, long sid, int mask,
			Boolean granting, Boolean auditSuccess, Boolean auditFailure) {
		this.aclObjectIdentity = aclObjectIdentity;
		this.aceOrder = aceOrder;
		this.sid = sid;
		this.mask = mask;
		this.granting = granting;
		this.auditSuccess = auditSuccess;
		this.auditFailure = auditFailure;
	}


	@Column(name = "ACL_OBJECT_IDENTITY", nullable = false)
	public long getAclObjectIdentity() {
		return this.aclObjectIdentity;
	}

	public void setAclObjectIdentity(long aclObjectIdentity) {
		this.aclObjectIdentity = aclObjectIdentity;
	}

	@Column(name = "ACE_ORDER", nullable = false)
	public int getAceOrder() {
		return this.aceOrder;
	}

	public void setAceOrder(int aceOrder) {
		this.aceOrder = aceOrder;
	}

	@Column(name = "SID", nullable = false)
	public long getSid() {
		return this.sid;
	}

	public void setSid(long sid) {
		this.sid = sid;
	}

	@Column(name = "MASK", nullable = false)
	public int getMask() {
		return this.mask;
	}

	public void setMask(int mask) {
		this.mask = mask;
	}

	@Column(name = "GRANTING", nullable = false, length = 1)
    public Boolean getGranting() {
		return granting;
	}

	public void setGranting(Boolean granting) {
		this.granting = granting;
	}

	@Column(name = "AUDIT_SUCCESS", nullable = false, length = 1)
	public Boolean getAuditSuccess() {
		return auditSuccess;
	}

	public void setAuditSuccess(Boolean auditSuccess) {
		this.auditSuccess = auditSuccess;
	}
	
	@Column(name = "AUDIT_FAILURE", nullable = false, length = 1)
	public Boolean getAuditFailure() {
		return auditFailure;
	}

	public void setAuditFailure(Boolean auditFailure) {
		this.auditFailure = auditFailure;
	}
	
	

}
