package com.xyz.acl.model;

// Generated 2009-12-20 12:00:06 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AclObjectIdentity generated by hbm2java
 */
@Entity
@Table(name = "acl_object_identity")
public class AclObjectIdentity  extends AbstractSecureObject {
	private long objectIdClass;
	private long objectIdIdentity;
	private Long parentObject;
	private Long ownerSid;
	private boolean entriesInheriting;

	public AclObjectIdentity() {
	}

	public AclObjectIdentity(long objectIdClass, long objectIdIdentity,
			boolean entriesInheriting) {
		this.objectIdClass = objectIdClass;
		this.objectIdIdentity = objectIdIdentity;
		this.entriesInheriting = entriesInheriting;
	}

	public AclObjectIdentity(long objectIdClass, long objectIdIdentity,
			Long parentObject, Long ownerSid, boolean entriesInheriting) {
		this.objectIdClass = objectIdClass;
		this.objectIdIdentity = objectIdIdentity;
		this.parentObject = parentObject;
		this.ownerSid = ownerSid;
		this.entriesInheriting = entriesInheriting;
	}

	@Column(name = "OBJECT_ID_CLASS", nullable = false)
	public long getObjectIdClass() {
		return this.objectIdClass;
	}

	public void setObjectIdClass(long objectIdClass) {
		this.objectIdClass = objectIdClass;
	}

	@Column(name = "OBJECT_ID_IDENTITY", nullable = false)
	public long getObjectIdIdentity() {
		return this.objectIdIdentity;
	}

	public void setObjectIdIdentity(long objectIdIdentity) {
		this.objectIdIdentity = objectIdIdentity;
	}

	@Column(name = "PARENT_OBJECT")
	public Long getParentObject() {
		return this.parentObject;
	}

	public void setParentObject(Long parentObject) {
		this.parentObject = parentObject;
	}

	@Column(name = "OWNER_SID")
	public Long getOwnerSid() {
		return this.ownerSid;
	}

	public void setOwnerSid(Long ownerSid) {
		this.ownerSid = ownerSid;
	}
	
	@Column(name = "ENTRIES_INHERITING", nullable = false, length = 1)
	public boolean isEntriesInheriting() {
		return entriesInheriting;
	}

	public void setEntriesInheriting(boolean entriesInheriting) {
		this.entriesInheriting = entriesInheriting;
	}



}
