package com.xyz.acl.model;

// Generated 2009-12-20 12:00:06 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclSid generated by hbm2java
 */
@Entity
@Table(name = "acl_sid",uniqueConstraints = @UniqueConstraint(columnNames = {
		"SID", "PRINCIPAL" }))
public class AclSid extends AbstractSecureObject {
	private char principal;
	private String sid;

	public AclSid() {
	}

	public AclSid(char principal, String sid) {
		this.principal = principal;
		this.sid = sid;
	}

	@Column(name = "PRINCIPAL", nullable = false, length = 1)
	public char getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(char principal) {
		this.principal = principal;
	}

	@Column(name = "SID", nullable = false)
	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

}
