package com.xyz.base.model;

// Generated 2009-10-31 14:39:21 by Hibernate Tools 3.2.4.GA

/**
 * DtpropertiesId generated by hbm2java
 */
public class DtPropertiesId implements java.io.Serializable {

	private int id;
	private String property;

	public DtPropertiesId() {
	}

	public DtPropertiesId(int id, String property) {
		this.id = id;
		this.property = property;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DtPropertiesId))
			return false;
		DtPropertiesId castOther = (DtPropertiesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getProperty() == castOther.getProperty()) || (this
						.getProperty() != null
						&& castOther.getProperty() != null && this
						.getProperty().equals(castOther.getProperty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getProperty() == null ? 0 : this.getProperty().hashCode());
		return result;
	}

}
