/*
 * Generated by ActionName
 * Template path: templates/java/JavaClass.vtl
 */
package com.xyz.system.server;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * 创建日期: 08-17-2009
 * 
 * XDoclet definition:
 * 
 * 作者:Val
 */
@Controller 
public class IndexAction {
	@RequestMapping("/index")
	public String execute() {
		return "login";
	}
}