/*
 * Generated by ActionName
 * Template path: templates/java/JavaClass.vtl
 */
package com.xyz.system.server;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.xyz.system.model.User;
import com.xyz.system.service.ISecurityService;
import com.xyz.util.JsonUtil;
import com.xyz.util.SpringSecurityUtil;

/** 
 * ActionName
 * 创建日期: 08-27-2009
 * 
 * XDoclet definition:
 * 作者:Val
 */
@Controller
public class UserAction  {
	@Autowired 
	private ISecurityService facade ;

	/** 
	 * Method execute
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@RequestMapping("/user/forward.do")
	public String forward(HttpServletRequest request, HttpServletResponse response) {
		return "userinfo";
	}
	@RequestMapping("/user/save.do")
	public String save(User model, HttpServletRequest request, HttpServletResponse response) {
		User user = SpringSecurityUtil.getCurrentUser();
		if(user!=null)
		{
			user.setRealName(model.getRealName());
		}else{
			user = model;
		}
		facade.saveUser(user);
		JsonUtil.formSubmitResult(response, true, "修改用户信息成功");
		return null;
	}
}