/*
 * Generated by ActionName
 * Template path: templates/java/JavaClass.vtl
 */
package com.xyz.system.server;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.xyz.system.model.Shop;
import com.xyz.system.model.User;
import com.xyz.system.task.ISysTask;
import com.xyz.util.SpringSecurityUtil;

/** 
 * ActionName
 */
@Controller
public class ValidateAction{
	
	  @Autowired @Qualifier("systemTask")
	  private ISysTask authTask;
	/** 
	 * 验证会话状态与淘宝授权状态
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@RequestMapping("/validate") 
	@ResponseBody
	public String validate(HttpServletRequest request, HttpServletResponse response) {
		//每隔八分钟刷新一次会话
		authTask.holdAuthorize();
		return "success";
	}
}