package com.xyz.system.model;

// Generated 2009-9-14 18:36:13 by Hibernate Tools 3.2.4.GA
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;

import com.xyz.base.model.BaseModel;

/**
 * SsAuthority generated by hbm2java
 */
@Entity @Table(name="Authority")
public class Authority extends BaseModel implements GrantedAuthority {
	@Basic
	private String role;
	@Basic
    private String displayName;

	@Basic
	private Set<String> resourceKeys; //当前权限拥有资源的KEY列表

	public Authority() {
	}

	public Authority(String name,String displayName) {
		this.displayName = displayName;
		this.role = name;
	}


	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Override
	public String getAuthority() {
		// TODO Auto-generated method stub
	  return this.role;
	}

	  public int hashCode() {
	        return this.role.hashCode();
	    }

	    public String toString() {
	        return this.role;
	    }

	    public int compareTo(GrantedAuthority ga) {
	        if (ga != null) {
	            String rhsRole = ga.getAuthority();

	            if (rhsRole == null) {
	                return -1;
	            }

	            return role.compareTo(rhsRole);
	        }
	        return -1;
	    }

		public String getRole() {
			return role;
		}

		public void setRole(String role) {
			this.role = role;
		}

		public Set<String> getResourceKeys() {
			return resourceKeys;
		}

		public void setResourceKeys(Set<String> resourceKeys) {
			this.resourceKeys = resourceKeys;
		}

}
