package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SavedSearch generated by hbm2java
 */
public class SavedSearch implements java.io.Serializable {

	private String id;
	private String name;
	private String searchModule;
	private boolean deleted;
	private Date dateEntered;
	private Date dateModified;
	private String assignedUserId;
	private String contents;
	private String description;

	public SavedSearch() {
	}

	public SavedSearch(String id, boolean deleted, Date dateEntered,
			Date dateModified) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
	}

	public SavedSearch(String id, String name, String searchModule,
			boolean deleted, Date dateEntered, Date dateModified,
			String assignedUserId, String contents, String description) {
		this.id = id;
		this.name = name;
		this.searchModule = searchModule;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.assignedUserId = assignedUserId;
		this.contents = contents;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSearchModule() {
		return this.searchModule;
	}

	public void setSearchModule(String searchModule) {
		this.searchModule = searchModule;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(String assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
