package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Schedulers generated by hbm2java
 */
public class Schedulers implements java.io.Serializable {

	private String id;
	private boolean deleted;
	private Date dateEntered;
	private Date dateModified;
	private String createdBy;
	private String modifiedUserId;
	private String name;
	private String job;
	private Date dateTimeStart;
	private Date dateTimeEnd;
	private String jobInterval;
	private Date timeFrom;
	private Date timeTo;
	private Date lastRun;
	private String status;
	private Boolean catchUp;

	public Schedulers() {
	}

	public Schedulers(String id, boolean deleted, Date dateEntered,
			Date dateModified, String name, String job, Date dateTimeStart,
			String jobInterval) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.name = name;
		this.job = job;
		this.dateTimeStart = dateTimeStart;
		this.jobInterval = jobInterval;
	}

	public Schedulers(String id, boolean deleted, Date dateEntered,
			Date dateModified, String createdBy, String modifiedUserId,
			String name, String job, Date dateTimeStart, Date dateTimeEnd,
			String jobInterval, Date timeFrom, Date timeTo, Date lastRun,
			String status, Boolean catchUp) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.createdBy = createdBy;
		this.modifiedUserId = modifiedUserId;
		this.name = name;
		this.job = job;
		this.dateTimeStart = dateTimeStart;
		this.dateTimeEnd = dateTimeEnd;
		this.jobInterval = jobInterval;
		this.timeFrom = timeFrom;
		this.timeTo = timeTo;
		this.lastRun = lastRun;
		this.status = status;
		this.catchUp = catchUp;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedUserId() {
		return this.modifiedUserId;
	}

	public void setModifiedUserId(String modifiedUserId) {
		this.modifiedUserId = modifiedUserId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Date getDateTimeStart() {
		return this.dateTimeStart;
	}

	public void setDateTimeStart(Date dateTimeStart) {
		this.dateTimeStart = dateTimeStart;
	}

	public Date getDateTimeEnd() {
		return this.dateTimeEnd;
	}

	public void setDateTimeEnd(Date dateTimeEnd) {
		this.dateTimeEnd = dateTimeEnd;
	}

	public String getJobInterval() {
		return this.jobInterval;
	}

	public void setJobInterval(String jobInterval) {
		this.jobInterval = jobInterval;
	}

	public Date getTimeFrom() {
		return this.timeFrom;
	}

	public void setTimeFrom(Date timeFrom) {
		this.timeFrom = timeFrom;
	}

	public Date getTimeTo() {
		return this.timeTo;
	}

	public void setTimeTo(Date timeTo) {
		this.timeTo = timeTo;
	}

	public Date getLastRun() {
		return this.lastRun;
	}

	public void setLastRun(Date lastRun) {
		this.lastRun = lastRun;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Boolean getCatchUp() {
		return this.catchUp;
	}

	public void setCatchUp(Boolean catchUp) {
		this.catchUp = catchUp;
	}

}
