package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SchedulersTimes generated by hbm2java
 */
public class SchedulersTimes implements java.io.Serializable {

	private String id;
	private boolean deleted;
	private Date dateEntered;
	private Date dateModified;
	private String schedulerId;
	private Date executeTime;
	private String status;

	public SchedulersTimes() {
	}

	public SchedulersTimes(String id, boolean deleted, Date dateEntered,
			Date dateModified, String schedulerId, Date executeTime,
			String status) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.schedulerId = schedulerId;
		this.executeTime = executeTime;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getSchedulerId() {
		return this.schedulerId;
	}

	public void setSchedulerId(String schedulerId) {
		this.schedulerId = schedulerId;
	}

	public Date getExecuteTime() {
		return this.executeTime;
	}

	public void setExecuteTime(Date executeTime) {
		this.executeTime = executeTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
