package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Tracker generated by hbm2java
 */
public class Tracker implements java.io.Serializable {

	private Integer id;
	private String monitorId;
	private String userId;
	private String moduleName;
	private String itemId;
	private String itemSummary;
	private Date dateModified;
	private String action;
	private String sessionId;
	private Boolean visible;
	private Boolean deleted;

	public Tracker() {
	}

	public Tracker(String monitorId) {
		this.monitorId = monitorId;
	}

	public Tracker(String monitorId, String userId, String moduleName,
			String itemId, String itemSummary, Date dateModified,
			String action, String sessionId, Boolean visible, Boolean deleted) {
		this.monitorId = monitorId;
		this.userId = userId;
		this.moduleName = moduleName;
		this.itemId = itemId;
		this.itemSummary = itemSummary;
		this.dateModified = dateModified;
		this.action = action;
		this.sessionId = sessionId;
		this.visible = visible;
		this.deleted = deleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMonitorId() {
		return this.monitorId;
	}

	public void setMonitorId(String monitorId) {
		this.monitorId = monitorId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getItemSummary() {
		return this.itemSummary;
	}

	public void setItemSummary(String itemSummary) {
		this.itemSummary = itemSummary;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
