package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UsersSignatures generated by hbm2java
 */
public class UsersSignatures implements java.io.Serializable {

	private String id;
	private Date dateEntered;
	private Date dateModified;
	private boolean deleted;
	private String userId;
	private String name;
	private String signature;
	private String signatureHtml;

	public UsersSignatures() {
	}

	public UsersSignatures(String id, Date dateEntered, Date dateModified,
			boolean deleted) {
		this.id = id;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.deleted = deleted;
	}

	public UsersSignatures(String id, Date dateEntered, Date dateModified,
			boolean deleted, String userId, String name, String signature,
			String signatureHtml) {
		this.id = id;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.deleted = deleted;
		this.userId = userId;
		this.name = name;
		this.signature = signature;
		this.signatureHtml = signatureHtml;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getSignatureHtml() {
		return this.signatureHtml;
	}

	public void setSignatureHtml(String signatureHtml) {
		this.signatureHtml = signatureHtml;
	}

}
