package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

/**
 * UsersFeeds generated by hbm2java
 */
public class UsersFeeds implements java.io.Serializable {

	private UsersFeedsId id;

	public UsersFeeds() {
	}

	public UsersFeeds(UsersFeedsId id) {
		this.id = id;
	}

	public UsersFeedsId getId() {
		return this.id;
	}

	public void setId(UsersFeedsId id) {
		this.id = id;
	}

}
