package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

/**
 * UsersLastImport generated by hbm2java
 */
public class UsersLastImport implements java.io.Serializable {

	private String id;
	private String assignedUserId;
	private String importModule;
	private String beanType;
	private String beanId;
	private boolean deleted;

	public UsersLastImport() {
	}

	public UsersLastImport(String id, boolean deleted) {
		this.id = id;
		this.deleted = deleted;
	}

	public UsersLastImport(String id, String assignedUserId,
			String importModule, String beanType, String beanId, boolean deleted) {
		this.id = id;
		this.assignedUserId = assignedUserId;
		this.importModule = importModule;
		this.beanType = beanType;
		this.beanId = beanId;
		this.deleted = deleted;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(String assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	public String getImportModule() {
		return this.importModule;
	}

	public void setImportModule(String importModule) {
		this.importModule = importModule;
	}

	public String getBeanType() {
		return this.beanType;
	}

	public void setBeanType(String beanType) {
		this.beanType = beanType;
	}

	public String getBeanId() {
		return this.beanId;
	}

	public void setBeanId(String beanId) {
		this.beanId = beanId;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
