package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Vcals generated by hbm2java
 */
public class Vcals implements java.io.Serializable {

	private String id;
	private boolean deleted;
	private Date dateEntered;
	private Date dateModified;
	private String userId;
	private String type;
	private String source;
	private String content;

	public Vcals() {
	}

	public Vcals(String id, boolean deleted, String userId) {
		this.id = id;
		this.deleted = deleted;
		this.userId = userId;
	}

	public Vcals(String id, boolean deleted, Date dateEntered,
			Date dateModified, String userId, String type, String source,
			String content) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.userId = userId;
		this.type = type;
		this.source = source;
		this.content = content;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
