package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * AclActions generated by hbm2java
 */
public class Action implements java.io.Serializable {

	private String id;
	private Date dateEntered;
	private Date dateModified;
	private String modifiedUserId;
	private String createdBy;
	private String name;
	private String category;
	private String acltype;
	private Integer aclaccess;
	private Boolean deleted;

	public Action() {
	}

	public Action(String id, Date dateEntered, Date dateModified,
			String modifiedUserId) {
		this.id = id;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.modifiedUserId = modifiedUserId;
	}

	public Action(String id, Date dateEntered, Date dateModified,
			String modifiedUserId, String createdBy, String name,
			String category, String acltype, Integer aclaccess, Boolean deleted) {
		this.id = id;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.modifiedUserId = modifiedUserId;
		this.createdBy = createdBy;
		this.name = name;
		this.category = category;
		this.acltype = acltype;
		this.aclaccess = aclaccess;
		this.deleted = deleted;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getModifiedUserId() {
		return this.modifiedUserId;
	}

	public void setModifiedUserId(String modifiedUserId) {
		this.modifiedUserId = modifiedUserId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getAcltype() {
		return this.acltype;
	}

	public void setAcltype(String acltype) {
		this.acltype = acltype;
	}

	public Integer getAclaccess() {
		return this.aclaccess;
	}

	public void setAclaccess(Integer aclaccess) {
		this.aclaccess = aclaccess;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
