package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UserPreferences generated by hbm2java
 */
public class UserPreferences implements java.io.Serializable {

	private String id;
	private String category;
	private boolean deleted;
	private Date dateEntered;
	private Date dateModified;
	private String assignedUserId;
	private String contents;

	public UserPreferences() {
	}

	public UserPreferences(String id, boolean deleted, Date dateEntered,
			Date dateModified, String assignedUserId) {
		this.id = id;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.assignedUserId = assignedUserId;
	}

	public UserPreferences(String id, String category, boolean deleted,
			Date dateEntered, Date dateModified, String assignedUserId,
			String contents) {
		this.id = id;
		this.category = category;
		this.deleted = deleted;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.assignedUserId = assignedUserId;
		this.contents = contents;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Date getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered) {
		this.dateEntered = dateEntered;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(String assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

}
