package com.xyz.system.model;

// Generated 2009-9-11 18:08:43 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UsersFeedsId generated by hbm2java
 */
public class UsersFeedsId implements java.io.Serializable {

	private String userId;
	private String feedId;
	private Integer rank;
	private Date dateModified;
	private boolean deleted;

	public UsersFeedsId() {
	}

	public UsersFeedsId(boolean deleted) {
		this.deleted = deleted;
	}

	public UsersFeedsId(String userId, String feedId, Integer rank,
			Date dateModified, boolean deleted) {
		this.userId = userId;
		this.feedId = feedId;
		this.rank = rank;
		this.dateModified = dateModified;
		this.deleted = deleted;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFeedId() {
		return this.feedId;
	}

	public void setFeedId(String feedId) {
		this.feedId = feedId;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersFeedsId))
			return false;
		UsersFeedsId castOther = (UsersFeedsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(
				castOther.getUserId())))
				&& ((this.getFeedId() == castOther.getFeedId()) || (this
						.getFeedId() != null
						&& castOther.getFeedId() != null && this.getFeedId()
						.equals(castOther.getFeedId())))
				&& ((this.getRank() == castOther.getRank()) || (this.getRank() != null
						&& castOther.getRank() != null && this.getRank()
						.equals(castOther.getRank())))
				&& ((this.getDateModified() == castOther.getDateModified()) || (this
						.getDateModified() != null
						&& castOther.getDateModified() != null && this
						.getDateModified().equals(castOther.getDateModified())))
				&& (this.isDeleted() == castOther.isDeleted());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getFeedId() == null ? 0 : this.getFeedId().hashCode());
		result = 37 * result
				+ (getRank() == null ? 0 : this.getRank().hashCode());
		result = 37
				* result
				+ (getDateModified() == null ? 0 : this.getDateModified()
						.hashCode());
		result = 37 * result + (this.isDeleted() ? 1 : 0);
		return result;
	}

}
